[build]
  base = "/client"
  command = "CI='' npm run build"
  publish = "build"
  functions = "netlify/functions"


[functions]
  external_node_modules = ["express"]
  node_bundler = "esbuild"

[dev]
    publish = "client/public"
    node_bundler = "esbuild"
    functions = "netlify/functions"

[[redirects]]
  from = "/test/*"
  status = 200
  to = ".netlify/functions/test/:splat"

[[redirects]]
from = "/api/v1/*"
status = 200
to = ".netlify/functions/api/:splat"